PreventiveMaintenanceSystem/Models/Entities/PanelCheck.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PreventiveMaintenanceSystem.Models.Entities
{
    public class PanelCheck
    {
        public int ID { get; set; }
        [Display(Name = "Panel #")]
        public int Number { get; set; }
        public string Tower { get; set; }
        [Display(Name = "Panel Sounder Output")]
        public bool SounderOutput { get; set; }
        [Display(Name = "Battery Connector")]
        public bool BatteryConnector { get; set; }
        [Display(Name = "Battery Voltage")]
        public decimal BatteryVoltage { get; set; }
        [Display(Name = "Inspection Date")]
        public DateTime InspectionDate { get; set; }
        [Required]
        public string Inspector { get; set; }
    }
}

PreventiveMaintenanceSystem/Models/Entities/SounderCheck.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PreventiveMaintenanceSystem.Models.Entities
{
    public class SounderCheck
    {
        public int ID { get; set; }
        public string Level { get; set; }
        public string Tower { get; set; }
        public bool MCP1 { get; set; }
        public bool MCP2 { get; set; }
        public bool Sounder1 { get; set; }
        public bool Sounder2 { get; set; }
        public string Remarks { get; set; }
        [Display(Name = "Inspection Date")]
        public DateTime InspectionDate { get; set; }
        public string Inspector { get; set; }
    }
}

PreventiveMaintenanceSystem/Models/ViewModels/PanelCheckViewModel.cs
using PreventiveMaintenanceSystem.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PreventiveMaintenanceSystem.Models.ViewModels
{
    public class PanelCheckViewModel : PanelCheck
    {
        public List<SelectListItem> ListOfTowers { get; set; }
    }
}

PreventiveMaintenanceSystem/Controllers/API/FDASController.cs
using PreventiveMaintenanceSystem.Manager;
using PreventiveMaintenanceSystem.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PreventiveMaintenanceSystem.Controllers.API
{
    public class FDASController : ControllerBase
    {
        [HttpPost]
        public ActionResult SoundCheckInsertByBatch(IEnumerable<SounderCheck> parameters)
        {
            SounderCheckManager manager = new SounderCheckManager();
            if (parameters.Count() > 0)
            {
                foreach (var item in parameters)
                {
                    manager.Insert(item);
                }
            }
            return Redirect("/fdas/sounderindex");
        }
    }
}

PreventiveMaintenanceSystem/Controllers/FDASController.cs
using Newtonsoft.Json.Linq;
using PreventiveMaintenanceSystem.Manager;
using PreventiveMaintenanceSystem.Models;
using PreventiveMaintenanceSystem.Models.Entities;
using PreventiveMaintenanceSystem.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PreventiveMaintenanceSystem.Controllers
{
    public class FDASController : Controller
    {
        private PanelCheckManager panelCheckManager = new PanelCheckManager();
        private SounderCheckManager sounderCheckManager = new SounderCheckManager();
        private InspectorManager inspectorManager = new InspectorManager();
        private DropdownManager ddManager = new DropdownManager();
        // GET: FDAS
        public ActionResult Index()
        {
            return View();
        }
        public void ReadyContextForView()
        {
            PanelCheckViewModel panelCheckViewModel = new PanelCheckViewModel();
            panelCheckViewModel.ListOfTowers = ddManager.TowerList();
            ViewBag.Context = panelCheckViewModel;
        }
        public void Floors(int bldg)
        {
            List<string> floors = new List<string>();
            floors.Add("Basement");
            floors.Add("Ground Floor");
            floors.Add("2nd Floor");
            floors.Add("3rd Floor");
            floors.Add("4th Floor");
            floors.Add("5th Floor");
            floors.Add("6th Floor");
            floors.Add("7th Floor");
            floors.Add("8th Floor");
            floors.Add("9th Floor");
            floors.Add("10th Floor");
            floors.Add("11th Floor");
            floors.Add("12th Floor");
            if (bldg == 0) // For One West
            {
                floors.RemoveAt(12);
                ViewBag.FloorList = floors;
            }
            if (bldg == 1) // For Two West Tower
            {
                ViewBag.FloorList = floors;
            }
        }
        public ActionResult SounderIndex()
        {
            return View(sounderCheckManager.SounderChecksGetAll());
        }
        // Sounder Insert for One West Tower 
        //[HttpGet]
        //public ActionResult OneWest()
        //{
        //    Floors(0);
        //    return View();
        //}
        //public ActionResult TwoWest()
        //{
        //    Floors(1);
        //    return View();
        //}
        [HttpGet]
        public ActionResult SounderCheck(int id)
        {
            int floorNo = id.Equals(2) ? 1 : 0;
            Floors(floorNo);
            ViewBag.TowerName = id.Equals(1) ? "One West" : "Two West";
            return View();
        }
        // Sounder Insert
        [HttpPost]
        public ActionResult SounderCheck(List<SounderCheck> sounderChecks)
        {
            foreach (var item in sounderChecks)
            {
                sounderCheckManager.Insert(item);
            }
            return Redirect("/fdas/sounderindex");
        }

        [HttpGet]
        public ActionResult EditSounderCheck(int id)
        {
            var model = sounderCheckManager.SounderCheckGetByID(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult EditSounderCheck(SounderCheck sounderCheck)
        {
            sounderCheckManager.Update(sounderCheck);
            return Redirect("/fdas/sounderindex");
        }
        // Homepage of Panel Check
        public ActionResult PanelIndex()
        {
            return View(panelCheckManager.PanelChecksGetAll());
        }
        [HttpGet]
        public ActionResult PanelCheck()
        {
            ReadyContextForView();
            return View();
        }

        [HttpPost]
        public ActionResult PanelCheck(PanelCheck panelCheck)
        {
            var defaultDate = DateTime.Now;
            panelCheck.InspectionDate = defaultDate;
            panelCheckManager.Insert(panelCheck);
            return Redirect("/fdas/panelindex");
        }
        [HttpGet]
        public ActionResult EditPanelCheck(int id)
        {
            var model = panelCheckManager.PanelCheckGetByID(id);
            model.InspectionDate = DateTime.Now;
            ReadyContextForView();
            return View(model);
        }

        [HttpPost]
        public ActionResult EditPanelCheck(PanelCheck panelCheck)
        {
            panelCheckManager.Update(panelCheck);
            return Redirect("/fdas/panelindex");
        }

        // Bulk insert using SQLBULKCOPY
        [HttpPost]
        public ActionResult SaveBulkSounderChecks(List<SounderCheck> sounderChecks)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    var date = DateTime.Now;
                    sounderChecks.ForEach(x => x.InspectionDate = date);

                    var result = sounderCheckManager.InsertBulk(sounderChecks);

                    if (result.IsSuccess)
                    {
                        ViewBag.Success = "Saved.";
                        TempData["Success"] = "Sounder check records successfully saved!";
                        return Redirect("/contact/edit/" + result.ID);
                    }
                    else
                    {
                        TempData["Error"] = result.ExceptionMessage;
                        ViewBag.Error = result.ExceptionMessage;
                    }
                }
                else
                {
                    string errorList = "";
                    foreach (ModelState modelState in ViewData.ModelState.Values)
                    {
                        foreach (ModelError error in modelState.Errors)
                        {
                            errorList += error.ErrorMessage + "<br>";
                        }
                    }
                    ViewBag.Error = errorList;
                }
            }
            catch (Exception error)
            {
                ViewBag.Error = error.Message;
            }

            return View(sounderChecks);
        }

    }
}

PreventiveMaintenanceSystem/Views/FDAS/EditPanelCheck.cshtml
@model PreventiveMaintenanceSystem.Models.Entities.PanelCheck

@{
    ViewBag.Title = "Edit Panel";
    var context = ViewBag.Context as PreventiveMaintenanceSystem.Models.ViewModels.PanelCheckViewModel;
    List<SelectListItem> panelList = new List<SelectListItem>();
    for (int i = 1; i < 6; i++)
    {
        panelList.Add(new SelectListItem
        {
            Text = i.ToString(),
            Value = i.ToString()
        });
    }
    List<SelectListItem> SoundOutput = new List<SelectListItem>();
    SoundOutput.Add(new SelectListItem
    {
        Text = "On",
        Value = "true"
    });
    SoundOutput.Add(new SelectListItem
    {
        Text = "Off",
        Value = "false"
    });

    List<SelectListItem> BatteryStatus = new List<SelectListItem>();
    BatteryStatus.Add(new SelectListItem
    {
        Text = "Good",
        Value = "true"
    });
    BatteryStatus.Add(new SelectListItem
    {
        Text = "No Good",
        Value = "false"
    });

    List<SelectListItem> TowerList = new List<SelectListItem>();
    TowerList.Add(new SelectListItem
    {
        Text = "One West",
        Value = "One West"
    });
    TowerList.Add(new SelectListItem
    {
        Text = "Two West",
        Value = "Two West"
    });
}
@section Styles
{
    <style>
        #panel-add {
            margin-top: 55px;
        }

        .bootstrap-tagsinput {
            width: 100% !important;
        }

        .dropdown-menu, span.twitter-typeahead .tt-menu {
            position: absolute;
            top: 100%;
            left: 0;
            z-index: 1000;
            display: none;
            float: left;
            min-width: 160px;
            padding: 10px;
            margin: 5px;
            font-size: 1rem;
            color: #373a3c;
            text-align: left;
            list-style: none;
            background-color: #fff;
            background-clip: padding-box;
            border: 1px solid rgba(0, 0, 0, 0.15);
            border-radius: 0.25rem;
        }

        span.twitter-typeahead .tt-menu {
            cursor: pointer;
        }

        *, *::before, *::after {
            -webkit-box-sizing: border-box;
            box-sizing: border-box;
        }
    </style>
}
<link href="~/Content/checkerview.css" rel="stylesheet" />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container" id="margin-index">
        @Html.AntiForgeryToken()
        <h3 class="font-weight-bold">Edit Panel</h3>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.DropDownListFor(model => model.Number, panelList, "Select Panel #", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tower, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @*@Html.EditorFor(model => model.Tower, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.Tower, context.ListOfTowers, "Select Tower", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Tower, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SounderOutput, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-12">
                @Html.DropDownListFor(model => model.SounderOutput, SoundOutput, "Select Sounder Output", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SounderOutput, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BatteryConnector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.DropDownListFor(model => model.BatteryConnector, BatteryStatus, "Select Battery Condition", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BatteryConnector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BatteryVoltage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.BatteryVoltage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BatteryVoltage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.InspectionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.InspectionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InspectionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <label>Inspector:</label>
                <input type="text" class="form-control" data-role="tagsinput" name="txtInspector" id="txtInspector" value="" readonly disabled />
                @Html.ValidationMessageFor(model => model.Inspector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
                <a href="/fdas/panelindex" class="btn btn-warning"><i class="fa fa-list"></i> Back to List</a>
            </div>
        </div>
    </div>

}
@section Scripts{
    @*<script src="~/Scripts/typeahead-inspector.js"></script>*@
    <script>
        $("#txtInspector").val("@Model.Inspector");
        //$('#txtInspector').tagsinput({
        //    'interactive': true
        //});
    </script>

}

PreventiveMaintenanceSystem/Views/FDAS/EditSounderCheck.cshtml
@model PreventiveMaintenanceSystem.Models.Entities.SounderCheck

@{
    ViewBag.Title = "Edit Sounder";
    List<SelectListItem> Status = new List<SelectListItem>();
    Status.Add(new SelectListItem
    {
        Text = "Select Status",
        Value = "true"
    });
    Status.Add(new SelectListItem
    {
        Text = "Good",
        Value = "true"
    });
    Status.Add(new SelectListItem
    {
        Text = "No Good",
        Value = "false"
    });
}

<h2>EditSounderCheck</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container" id="panel-edit">
        @Html.AntiForgeryToken()
        <h3 class="font-weight-bold">Edit Sounder</h3>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Tower, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Tower, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Tower, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Level, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @*@Html.EditorFor(model => model.Tower, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.EditorFor(model => model.Level, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Level, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MCP1, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-12">
                @Html.DropDownListFor(model => model.MCP1, Status, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MCP1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MCP2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.DropDownListFor(model => model.MCP2, Status, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MCP2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sounder1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.DropDownListFor(model => model.Sounder1, Status, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sounder1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sounder2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.DropDownListFor(model => model.Sounder2, Status, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sounder2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InspectionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @*@Html.TextAreaFor(model => model.InspectionDate, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="text" class="form-control" name="InspectionDate" id="InspectionDate" value="@Model.InspectionDate.ToString("MM/dd/yyyy")" readonly />
                @Html.ValidationMessageFor(model => model.InspectionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <label>Inspector:</label>
                <input type="text" class="form-control" data-role="tagsinput" name="txtInspector" id="txtInspector" value="" readonly disabled />
                @Html.ValidationMessageFor(model => model.Inspector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
                <a href="/fdas/sounderindex" class="btn btn-warning"><i class="fa fa-list"></i> Back to List</a>
            </div>
        </div>
    </div>

}
@section Scripts{
    <script>
        $("#txtInspector").val("@Model.Inspector");
    </script>
}

PreventiveMaintenanceSystem/Views/FDAS/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <hr />
    <h1>Preventive Maintenance</h1>
    <p class="lead">Inspect Device:</p>

    <a href="/FDAS/PanelIndex" class="btn btn-primary btn-lg"><i class="fa fa-dashboard"></i> Panel Checker</a>
    <a href="/FDAS/SounderIndex" class="btn btn-primary btn-lg"><i class="fa fa-volume-up"></i> Sounder Checker</a>
</div>

PreventiveMaintenanceSystem/Views/FDAS/PanelCheck.cshtml
@model PreventiveMaintenanceSystem.Models.Entities.PanelCheck

@{
    ViewBag.Title = "Panel Check";
    var context = ViewBag.Context as PreventiveMaintenanceSystem.Models.ViewModels.PanelCheckViewModel;
    List<SelectListItem> panelList = new List<SelectListItem>();
    for (int i = 1; i < 6; i++)
    {
        panelList.Add(new SelectListItem
        {
            Text = i.ToString(),
            Value = i.ToString()
        });
    }
    List<SelectListItem> SoundOutput = new List<SelectListItem>();
    SoundOutput.Add(new SelectListItem
    {
        Text = "On",
        Value = "true"
    });
    SoundOutput.Add(new SelectListItem
    {
        Text = "Off",
        Value = "false"
    });

    List<SelectListItem> BatteryStatus = new List<SelectListItem>();
    BatteryStatus.Add(new SelectListItem
    {
        Text = "Good",
        Value = "true"
    });
    BatteryStatus.Add(new SelectListItem
    {
        Text = "No Good",
        Value = "false"
    });
}

@using (Html.BeginForm("PanelCheck", "FDAS", FormMethod.Post))
{
    <div class="container" id="margin-index">
        @Html.AntiForgeryToken()
        <h3 class="font-weight-bold">Inspect Panel</h3>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.DropDownListFor(model => model.Number, panelList, "Select Panel #", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tower, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @*@Html.EditorFor(model => model.Tower, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.DropDownListFor(model => model.Tower, Model.ListOfTowers, new { @class = "form-control" })*@
                @Html.DropDownListFor(model => model.Tower, context.ListOfTowers, "Select Tower", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Tower, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SounderOutput, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-12">
                @Html.DropDownListFor(model => model.SounderOutput, SoundOutput, "Select Sounder Output", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SounderOutput, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BatteryConnector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.DropDownListFor(model => model.BatteryConnector, BatteryStatus, "Select Battery Condition", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BatteryConnector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BatteryVoltage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.BatteryVoltage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BatteryVoltage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.InspectionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.InspectionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InspectionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <label>Inspector:</label>
                <input type="text" name="Inspector" id="Inspector" value="" />
                @Html.ValidationMessageFor(model => model.Inspector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
                <a href="/fdas/panelindex" class="btn btn-warning"><i class="fa fa-list"></i> Back to List</a>
            </div>
        </div>
    </div>

}
@section Scripts
{
    <script src="~/Scripts/typeahead-inspector.js"></script>
}

PreventiveMaintenanceSystem/Views/FDAS/SounderCheck.cshtml
@model List<PreventiveMaintenanceSystem.Models.Entities.SounderCheck>
@{
    ViewBag.Title = "Inspect " + ViewBag.TowerName;
    List<SelectListItem> Status = new List<SelectListItem>();
    Status.Add(new SelectListItem
    {
        Text = "Select Status",
        Value = "true"
    });
    Status.Add(new SelectListItem
    {
        Text = "Good",
        Value = "true"
    });
    Status.Add(new SelectListItem
    {
        Text = "No Good",
        Value = "false"
    });

}
<div class="container" id="sounder-add">
    @using (Html.BeginForm("SounderCheck", "FDAS", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        <h4 style="float: left">Inspect @ViewBag.TowerName</h4>
        <hr />
        <a href="/fdas/sounderindex" class="btn btn-warning" id="back"><i class="fa fa-list"></i> Back to List</a>
        <br />
        <div class="col-md-6" style="float: left;">
            <label>Inspector:</label>
            <input type="text" class="form-control" name="Inspector" id="Inspector">
        </div>
        <table class="table" id="tblSounder">
            @foreach (var item in ViewBag.FloorList)
            {

                <thead>
                    <tr>
                        <th>Level</th>
                        <th>MCP1</th>
                        <th>MCP2</th>
                        <th>Sounder1</th>
                        <th>Sounder2</th>
                        <th>Remarks</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td hidden>
                            <input type="text" class="form-control" name="Tower" id="Tower" value="@ViewBag.TowerName">
                        </td>
                        <td>
                            <input type="text" class="form-control" name="Level" id="Level" value="@item" readonly>
                        </td>
                        <td>
                            @Html.DropDownList("MCP1", Status, new { @class = "form-control" })
                        </td>
                        <td>
                            @Html.DropDownList("MCP2", Status, new { @class = "form-control" })
                        </td>
                        <td>
                            @Html.DropDownList("Sounder1", Status, new { @class = "form-control" })
                        </td>
                        <td>
                            @Html.DropDownList("Sounder2", Status, new { @class = "form-control" })
                        </td>

                        <td>
                            <textarea name="Remarks" id="Remarks" class="form-control"></textarea>
                        </td>
                    </tr>
                </tbody>
            }
        </table>
        <div class="form-group">
            <div class="col-md-12">
                <button class="btn btn-primary" type="submit" id="btnSave"><i class="fa fa-save"></i> Save</button>
            </div>
        </div>
    }
</div>
@section Scripts{
    <script src="~/Scripts/typeahead-inspector.js"></script>
    <script src="~/Scripts/posting-checks.js"></script>
}